# container-based build
sudo: false

language: scala

env:
  - JAVA_OPTS="-DSKIP_FLAKY=true -Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.11
  - 2.12.4

jdk:
  - oraclejdk8

notifications:
  hipchat:
    rooms:
      secure: qoCpyYilDuXnWSquICCKRhuHhlOSS5WMsnna0yLAk46O2o2woitt0kMQM3fkEeqYtnYxH+K12aIShkC95BCKQ2cJbjR4OhNyTY9ZakgeTrdufAu7HwH1W+yxrdnXvmRbvH5uxgq/O0SerteL8gfIwHJRcaUQeswZJyBvD4G0CKU=

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test twitter-server
  - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION update

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
